name: 'From alembic to flyway - Postgres Migration'
description: 'Run migrations using your Github Action'
inputs:
  flyway_user:
    description: 'User for flyway connection'
    required: true
    default: ''
  flyway_pass:
    description: 'Password for flyway connection'
    required: true
    default: ''
  flyway_host:
    description: 'Host for flyway connection'
    required: true
    default: ''
  db_url:
    description: 'Host for general connection'
    required: true
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'